### ISSUE TITLE
(Endpoint) - Profile details

### ISSUE THREAD

**Issue by emiliogonmar2002** [13th-office/IBM-SkillBoard#96] opened 2023-04-27 18:13 UTC
This endpoint should return all profile details for a user for ProfileScreen

The route should be dynamic depending the user ID

#### Response body
Object with user info, user teams and user certificates

```
{
  user: {
    id: "cr7id",
    name: "Cristiano",
    last_name: "Ronaldo",
    role: "Bicho",
    email: "cr7@ibm.com",
  },
  team: [
    {
      team: {
        id: "1",
        team_name: "Backend Management",
      },
      manager: {
        id: "id",
        name: "Camello",
        last_name: "Petrolero",
        email: "camello@ibm.com",
        role: "Camello Manager",
      },
    },
    ...
  ],
  cerificates: [
    {
      id: "dsadsa",
      name: "Azure DevOps Certification",
      type: "Industry",
      categories: [
        { id: "1234", name: "Azure" },
        { id: "12345", name: "DevOps" },
      ],
      expiration_date: "2024-04-01",
    },
    ...
  ],
}
```

**Comment by gonzalpi** [comment] 2023-04-27 18:38
Duplicate of #36, copio y pego esta info allá

**Closed by gonzalpi** 2023-04-27 18:38 UTC
